version: "3.9"
services:
  rollout-frontend:
    build: ./packages/@rollout/frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://rollout-backend:4000
    depends_on:
      - rollout-backend
  rollout-backend:
    build: ./packages/@rollout/backend
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      DATABASE_URL: file:dev.db
      DATABASE: sqlite
